### ISSUE TITLE
Please Reply 

### ISSUE THREAD

**Issue by Pawansingh333** [SP-l33t/Dogiators-Telethon#4]
Here’s the translation of your message into English:

I and users like me appreciate your hard work on all these bots. Thank you! Your bots make you special on GitHub because all these bots are built using Pyrogram, but in my eyes, you are the first developer to use Telethon. I am not a developer, but I know enough to understand that using Telethon requires a skilled developer. For all these bots, I give you a star, and if I receive some USDT in the airdrop, I will share some with you.

I have a request: please create bots for all the tapping bots on Telegram. I also have a question: is it safe to use Pyrogram and Telethon? I have been running Pyrogram bots for a long time, and all my accounts are safe. Now, I am using Telethon, so will my accounts remain safe, or can Telegram block my accounts because of Telethon? Please reply.

Thanks!

**Comment by SP-l33t** [comment]
I'm creating new bots when I have enought time for it. Also trying to improve all the existing bots.
Telethon isn't much harder to use than Pyrogram. Most of the developers just copy each-others templates. That's why everyone uses Pyrogram.

Sadly, nothing is 100% safe. I know for sure that people are getting banned for using either: pyrogram or telethon.
For me, using Telethon was completely safe until 2 of my most recent accounts got banned.

The only big advantage of Telethon is that you can buy .session files and start using them asap, w/o the need of logging in.

As I said, nothing is 100% safe. Some of the users of my bots also reported that they got all sessions disconnected (or even account banned) for using my bots. https://github.com/SP-l33t/Dogiators-Telethon/issues/1
Sadly, it's something about Telegram anti-fraud protection and I don't have a solution.

**Comment by Pawansingh333** [comment]
"Thank you for your reply. I would like to say that whether you use Telethon or Pyrogram, it's the same for Telegram."

**Comment by SP-l33t** [comment]
I don't know if it's the same. Some people get banned for using pyrogram, some for using telethon.
Not sure, if either one is safer than another one.
Also, no idea how to make it any safer. I already tried a lot of things.

**Comment by airdrophunter9568** [comment]
Can you please Make bot for termux
